src/main/java/org/folio/auth/authtoken_module/MainVerticle.java
The "import com.sun.xml.internal.messaging.saaj.util.Base64;" should not used. Changed to use "import java.util.Base64;".
=> Avoid using sun internal package

src/main/java/org/folio/auth/authtoken_module/impl/ModulePermissionsSource.java
The request's timeout is completely unrelated to the underlying HTTP connection's keep-alive idle timeout. By default the connection is kept open until the vertx gets closed.
=> Remove HTTP-keep-alive idle timeout

src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java, src/main/java/org/folio/auth/authtokenmodule/PermissionsSource.java, src/main/java/org/folio/auth/authtokenmodule/impl/DummyPermissionsSource.java, src/main/java/org/folio/auth/authtokenmodule/impl/ModulePermissionsSource.java
Fixes concurrency issue with tenant. Remove setAuthApiKey method from
interface (not in use).
=> Avoid storing per-request items in PermissionsSource MODAT-29

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODAT-57 FOLIO-2358 manage container memory

src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
The theroy is that the user lookup does not obey dummy permissions
which do NOT have user info associated with them, eg permissions
lookup is disabled for that and should be too for user lookup.
This should not be merged. Can be me much prettier.
=> Attempt at fixing FOLIO-2366

pom.xml
Since moving to log4j2 (https://github.com/folio-org/mod-authtoken/pull/70) we've run into an issue with `log4j2Plugins.dat` colliding with those from 3rd party dependencies while shading.  
See: https://issues.apache.org/jira/browse/LOG4J2-673.
See: https://issues.folio.org/browse/MODAT-62
Use a shade plugin transformer which merges the various `log4jPlugins.dat` files.
See https://github.com/edwgiz/maven-shaded-log4j-transformer
=> MODAT-62 - Issue with log4j configuration

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/auth/authtokenmodule/AuthRoutingEntry.java, src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java, src/main/java/org/folio/auth/authtokenmodule/PermService.java, src/main/java/org/folio/auth/authtokenmodule/impl/ModulePermissionsSource.java, src/test/java/org/folio/auth/authtokenmodule/PermServiceTest.java
In OKAPI-837, we automatically convert module permissions to a permission set. Unfortunately mod-authtoken does not expand permission set to permissions for certain scenarios where no real user id is involved. For example during initial login or Okapi timer based system calls. This PR is to address this issue.
=> MODAT-72 Expand module permission set

descriptors/ModuleDescriptor-template.json
System is not building because okapi 3.0.0 is out and permissionsRequired is required.
=> Provide permissionsRequired MODAT-77

src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java
In order to allow tokens to be cached we need to remove the requestId claim.  AFAIK this isn't being used anyway.
https://issues.folio.org/browse/MODAT-86
=> MODAT-86: Remove requestId from token claims

Jenkinsfile, pom.xml, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
Migrate to JDK11
* Upgrade rest assured due to https://github.com/rest-assured/rest-assured/issues/1175
* Specify the jdk11 build node in Jenkinsfile
* Update maven compiler plugin configuration
See https://issues.folio.org/browse/MODAT-88
=> MODAT-88: migrate to JDK11

Dockerfile
See https://dev.folio.org/faqs/how-to-specify-backend-java-ci/
=> MODAT-88 Dockerfile use new base image jdk11

README.md
mod-authtoken's command line options are pretty sparsely documented. This is an attempt to help out, based on fairly superficial code inspection. Please feel free to correct errors and improve.
=> Update README.md to document command line options and system properties.

src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
As X-Okapi-Module-Tokens should be returned even in case of errors
so that pre/post filters can be invoked with proper module token. See MODAT-38
=> Partly revert MODAT-107

src/main/java/org/folio/auth/authtokenmodule/tokens/Token.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
NPE happened when user_id is not present in claims.
=> Fix user id match check MODAT-116

src/main/java/org/folio/auth/authtokenmodule/impl/ModulePermissionsSource.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java, src/test/java/org/folio/auth/authtokenmodule/PermsMock.java
When mod-authtoken fetches permissions for a user it calls
/perms/users?query=userId=={userId}
followed by:
/perms/users/{permUserId}/permissions?expanded=true
This can be changed to one call:
/perms/users/{userId}/permissions?expanded=true&indexField=userId
=> Redundant web service request MODAT-117

src/main/java/org/folio/auth/authtokenmodule/AuthRoutingEntry.java, src/main/java/org/folio/auth/authtokenmodule/AuthorizeApi.java, src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
The tenant call when recognized is just postponed to be handled later.
=> Always invoke filter (except for admin health).

pom.xml
Update Vert.x from 4.2.4 to 4.2.5 fixing pool bugs: https://github.com/vert-x3/wiki/wiki/4.2.5-Release-Notes
Update nimbus-jose-jwt from 7.9 to 9.20;
this indirectly removes the dependency on net.minidev:json-smart:2.3 and fixes denial of service (DoS) vulnerability reports: https://nvd.nist.gov/vuln/detail/CVE-2021-27568 https://nvd.nist.gov/vuln/detail/CVE-2021-31684
Update all other dependencies to latest stable versions:
* okapi-common from 4.12.0 to 4.13.0
* rest-assured from 4.4.0 to 4.5.1
* mockito-core from 3.3.3 to 4.3.1
=> MODAT-125: Update dependencies (CVE-2021-27568, CVE-2021-31684)

README.md, src/main/java/org/folio/auth/authtokenmodule/tokens/Token.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
As a sysop I would like to read some hint in the log how to fix the configuration when "Invalid token" might be caused by a wrong jwt.signing.key.
Use case 1:
Given that jwt.signing.key is not set and mod-authtoken is restarted
When using a token that has been issued before the restart that causes an "Invalid token" error
Then the log should indicate this it might be caused by the mod-authtoken restart.
Use case 2:
Given that a cluster of multiple instances of mod-authtoken has been configured with different jwt.signing.key values.
When using a token that has been issued by an instance with different key and getting an "Invalid token" error.
Then the log should indicate this it might be caused by different keys.
=> MODAT-128: jwt.signing.key hint on BadSignatureException

src/test/java/org/folio/auth/authtokenmodule/MainVerticleTest.java
Use free port as done in all other tests. Thus tests will be able to work on systems where 8081 is already in use.
=> Use free port in test

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, src/main/resources/openapi/token-1.0.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODAT-145 Use GitHub Workflows api-lint and api-schema-lint and api-doc

README.md, src/main/java/org/folio/auth/authtokenmodule/tokens/Token.java, src/main/java/org/folio/auth/authtokenmodule/tokens/TokenValidationContext.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
https://issues.folio.org/browse/MODAT-148
**Overview:**
Currently cross tenant requests allowed only in case when core mod-users /user-tenants response has total > 0 , it means that corresponding tenant added to consortium and we allow cross-tenant request. One more level of protection will be added by using a new system property:
'allow.cross.tenant.requests'. If this propertyis not set - cross tenant requests will be denied, in another case - standard checking of /user-tenant endpoint should be done as it doing now.
**Implementation Approach:**
ValidateTenantMismatch method is adjusted to look into presence of 'allow.cross.tenant.requests' [Code](https://github.com/folio-org/mod-authtoken/blob/master/src/main/java/org/folio/auth/authtokenmodule/tokens/Token.java#L292)
If system property …
=> [MODAT-148]. Allow cross tenant requests only when special system property variable presented

descriptors/ModuleDescriptor-template.json
We are trying to simplify local development in multi-tenant mode. Now mod-authtoken in local vagrant does not support cross tenant requests, so to run some consortia functionality and karate tests locally we need to re-run mod-authtoken with property allow.cross.tenant.requests.enabled.
We want to minimize effort for local setup, especially when redeploying a mod-auth token is not a very trivial process.
Vagrant build should take this property from module descriptor, hosting providers do not use module descriptor defaults, they overriding  with their custom values, so this property will not be set by default
=> Add running application in consortia mode locally without redeploying mod-authtoken

src/main/java/org/folio/auth/authtokenmodule/apis/RouteApi.java, src/main/java/org/folio/auth/authtokenmodule/tokens/RefreshToken.java, src/main/java/org/folio/auth/authtokenmodule/tokens/Token.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java, src/test/java/org/folio/auth/authtokenmodule/UsersMock.java
https://issues.folio.org/browse/MODAT-149
The 2 changes made here:
- Remove returning of failed future for refresh token when tenantId in headers do not match with tenantId in token. Instead common validation method used that allows cross tenant requests when all conditions met
- Refactor RefreshToken to use tenantId from token instead of headers to make it compatible with ECS when tenantId in header and token can be different, in this case need to use tenantId from token claims
=> MODAT-149. Make RTR compatible with ECS

src/main/java/org/folio/auth/authtokenmodule/apis/FilterApi.java, src/test/java/org/folio/auth/authtokenmodule/AuthTokenTest.java
https://issues.folio.org/browse/MODAT-160
This doesn't change all uses of the `403` response code, only the one which is causing trouble for the front end developers. `403` is still returned when the user id in `X-Okapi` and the token don't match. I think it is fine to still have other cases that return `403`. The key here is that we no longer use it for missing tokens.
=> MODAT-160: When a token isn't present in a request, return 400 rather than 403

descriptors/ModuleDescriptor-template.json, src/test/java/org/folio/auth/authtokenmodule/TokenTest.java
https://issues.folio.org/browse/MODAT-159
=> MODAT-159: allow.cross.tenant.requests=false to disable consortia options
